<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BankingApp.Worker-8ff110a8-9092-4c97-b1a0-e59b7d0d87cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\BankingApp.Application\BankingApp.Application.csproj" />
    <ProjectReference Include="..\..\backend\BankingApp.Infrastructure\BankingApp.Infrastructure.csproj" />
  </ItemGroup>
</Project>
