// <auto-generated />
using System;
using BankingApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankingAppDbContext))]
    partial class BankingAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingApp.Domain.Entities.AccessTokenRevocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("AccessTokenRevocations", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            AccountNumber = "BA-000001-CHECKING",
                            AccountType = "Checking",
                            Balance = 20000.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            UserId = new Guid("9a99a021-b892-4f5a-bd98-36a5afbf0c79")
                        },
                        new
                        {
                            Id = new Guid("6e4ac9f4-28d0-4f6a-b8c4-c7937f9a5ae3"),
                            AccountNumber = "BA-000001-SAVINGS",
                            AccountType = "Savings",
                            Balance = 5000.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            UserId = new Guid("9a99a021-b892-4f5a-bd98-36a5afbf0c79")
                        },
                        new
                        {
                            Id = new Guid("deed75d2-e898-4c2d-a7e3-2fa1152d7222"),
                            AccountNumber = "BA-000002-CHECKING",
                            AccountType = "Checking",
                            Balance = 350.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            UserId = new Guid("f5573a40-f822-45c4-a841-b6ab5d5a0c49")
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.AdminUserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DefaultItemsPerPage")
                        .HasColumnType("int");

                    b.Property<string>("FirstDayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumberFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SidebarStyle")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminUserPreferences", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Action", "EntityType");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.BankCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.ToTable("BankCards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8f0f3aa-e7d3-460c-86ff-6cfe0f5105dd"),
                            AccountId = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            Brand = "Mastercard",
                            CardNumber = "4562112245957852",
                            CardholderName = "Demo Customer",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cvv = "6986",
                            ExpiryDate = new DateTime(2030, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("741fc77c-fec7-4b53-92df-d664d14935e8"),
                            AccountId = new Guid("6e4ac9f4-28d0-4f6a-b8c4-c7937f9a5ae3"),
                            Brand = "Mastercard",
                            CardNumber = "4562444455550001",
                            CardholderName = "Demo Customer",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cvv = "315",
                            ExpiryDate = new DateTime(2030, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("62f3cd21-d263-40ca-ae58-07d13f7c5897"),
                            AccountId = new Guid("deed75d2-e898-4c2d-a7e3-2fa1152d7222"),
                            Brand = "Mastercard",
                            CardNumber = "5425233430109903",
                            CardholderName = "Yamilet Recipient",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cvv = "417",
                            ExpiryDate = new DateTime(2030, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.CardRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ApprovedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DocumentsRequestNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DocumentsRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAccountId");

                    b.HasIndex("ApprovedCardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardRequests", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.CardRequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardRequestId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("CardRequestDocuments", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisbursementTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MaturityDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NextPaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OriginalPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRepayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("DisbursementTransactionId");

                    b.HasIndex("LoanApplicationId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] = N'Active'");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AnnualInterestRateSnapshot")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimatedMonthlyPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedTotalInterest")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedTotalRepayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoanPurposeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("LoanProductId");

                    b.HasIndex("LoanPurposeId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] = N'Pending'");

                    b.HasIndex("Status", "SubmittedAtUtc");

                    b.HasIndex("UserId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("LoanApplications", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoanPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingPrincipalAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ScheduledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("LoanPaymentId")
                        .IsUnique()
                        .HasFilter("[LoanPaymentId] IS NOT NULL");

                    b.HasIndex("LoanId", "InstallmentNumber")
                        .IsUnique();

                    b.HasIndex("LoanId", "Status", "DueDateUtc");

                    b.ToTable("LoanInstallments", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoanInstallmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoanInstallmentId")
                        .IsUnique();

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("LoanId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("LoanId", "PaidAtUtc");

                    b.ToTable("LoanPayments", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MinPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TermStepMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Currency");

                    b.HasIndex("IsActive");

                    b.ToTable("LoanProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8dc061-237f-4bb4-89c1-32d41dc6f001"),
                            AnnualInterestRate = 6.50m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "BAM",
                            Description = "Fixed-rate personal loan in BAM.",
                            IsActive = true,
                            MaxPrincipal = 50000m,
                            MaxTermMonths = 60,
                            MinPrincipal = 1000m,
                            MinTermMonths = 6,
                            Name = "Personal Loan BAM",
                            TermStepMonths = 6,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f8dc061-237f-4bb4-89c1-32d41dc6f002"),
                            AnnualInterestRate = 5.75m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            Description = "Fixed-rate personal loan in EUR.",
                            IsActive = true,
                            MaxPrincipal = 25000m,
                            MaxTermMonths = 60,
                            MinPrincipal = 500m,
                            MinTermMonths = 6,
                            Name = "Personal Loan EUR",
                            TermStepMonths = 6,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f8dc061-237f-4bb4-89c1-32d41dc6f003"),
                            AnnualInterestRate = 6.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Fixed-rate personal loan in USD.",
                            IsActive = true,
                            MaxPrincipal = 25000m,
                            MaxTermMonths = 60,
                            MinPrincipal = 500m,
                            MinTermMonths = 6,
                            Name = "Personal Loan USD",
                            TermStepMonths = 6,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "Type", "EntityType", "EntityId")
                        .IsUnique()
                        .HasFilter("[EntityType] IS NOT NULL AND [EntityId] IS NOT NULL");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.ReferenceDataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.HasIndex("Type", "IsActive", "SortOrder");

                    b.ToTable("ReferenceDataItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "GENERAL",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "General purpose",
                            SortOrder = 10,
                            Type = "loan-purposes",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "HOME",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Home improvement",
                            SortOrder = 20,
                            Type = "loan-purposes",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "EDUCATION",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Education",
                            SortOrder = 30,
                            Type = "loan-purposes",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "IDENTITY",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Identity document",
                            SortOrder = 10,
                            Type = "document-types",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "PROOF_OF_INCOME",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Proof of income",
                            SortOrder = 20,
                            Type = "document-types",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "BANK_STATEMENT",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Bank statement",
                            SortOrder = 30,
                            Type = "document-types",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "GENERAL",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "General",
                            SortOrder = 10,
                            Type = "transaction-categories",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "TRANSFER",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Transfer",
                            SortOrder = 20,
                            Type = "transaction-categories",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "LOAN",
                            CreatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Loan",
                            SortOrder = 30,
                            Type = "transaction-categories",
                            UpdatedAtUtc = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.ReportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("ReportJobs", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoLogoutWarningMinutes")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CompanyPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableDataCaching")
                        .HasColumnType("bit");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SystemShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DestinationAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentsRequestNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DocumentsRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHighRiskReview")
                        .HasColumnType("bit");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid?>("TransactionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TransferAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransferCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Transfer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReferenceNumber");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8e0dbf7-536f-4301-99c7-5b3a1e03f450"),
                            AccountId = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            Amount = 20050.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial checking deposit",
                            IsHighRiskReview = false,
                            ReferenceNumber = "TXN-20260101-0001",
                            Status = "Completed",
                            Type = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("fd261404-8751-4faa-bffa-cdf7ea592903"),
                            AccountId = new Guid("6e4ac9f4-28d0-4f6a-b8c4-c7937f9a5ae3"),
                            Amount = 5000.00m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial savings deposit",
                            IsHighRiskReview = false,
                            ReferenceNumber = "TXN-20260101-0002",
                            Status = "Completed",
                            Type = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("4a6e449e-6397-45f6-a446-5936e882c401"),
                            AccountId = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            Amount = -50.00m,
                            CreatedAtUtc = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Demo transfer to Yamilet Recipient",
                            DestinationAccountId = new Guid("deed75d2-e898-4c2d-a7e3-2fa1152d7222"),
                            DestinationAmount = 50.00m,
                            IsHighRiskReview = false,
                            ReferenceNumber = "TXN-20260825-DEMO-RECENT",
                            SourceAccountId = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            Status = "Completed",
                            TransactionCategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            TransferAmount = 50.00m,
                            TransferCurrency = "USD",
                            Type = "Transfer"
                        },
                        new
                        {
                            Id = new Guid("4a6e449e-6397-45f6-a446-5936e882c402"),
                            AccountId = new Guid("deed75d2-e898-4c2d-a7e3-2fa1152d7222"),
                            Amount = 50.00m,
                            CreatedAtUtc = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transfer from BA-000001-CHECKING",
                            DestinationAccountId = new Guid("deed75d2-e898-4c2d-a7e3-2fa1152d7222"),
                            DestinationAmount = 50.00m,
                            IsHighRiskReview = false,
                            ReferenceNumber = "TXN-20260825-DEMO-RECENT",
                            SourceAccountId = new Guid("dbdd0766-a83e-4a7d-944c-af7d0373ff50"),
                            Status = "Completed",
                            TransactionCategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            TransferAmount = 50.00m,
                            TransferCurrency = "USD",
                            Type = "Transfer"
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.TransactionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDocuments", (string)null);
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePhotoContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ProfilePhotoUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a99a021-b892-4f5a-bd98-36a5afbf0c79"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mobile@bankingapp.local",
                            FirstName = "Demo",
                            IsDeleted = false,
                            LastName = "Customer",
                            PasswordHash = "PBKDF2-SHA256.100000.AQIDBAUGBwgJCgsMDQ4PEA==.1n/kUWC8lKsVwbzvVqx46PhnAJHTK4Pvs6t0RwMyEOQ=",
                            PhoneNumber = "+38761111222",
                            Role = "Customer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("dd72f286-0cf8-44ad-81ea-d85c5964d29d"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bankingapp.local",
                            FirstName = "Desktop",
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "PBKDF2-SHA256.100000.ERITFBUWFxgZGhscHR4fIA==.3+i0Vv41HWR1ofVLRyJthACrUOkA/W2oSnAkMKm57ak=",
                            PhoneNumber = "+38762222333",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("f5573a40-f822-45c4-a841-b6ab5d5a0c49"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "recipient@bankingapp.local",
                            FirstName = "Yamilet",
                            IsDeleted = false,
                            LastName = "Recipient",
                            PasswordHash = "PBKDF2-SHA256.100000.AQIDBAUGBwgJCgsMDQ4PEA==.1n/kUWC8lKsVwbzvVqx46PhnAJHTK4Pvs6t0RwMyEOQ=",
                            PhoneNumber = "+38763333444",
                            Role = "Customer",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.AdminUserPreferences", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("BankingApp.Domain.Entities.AdminUserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.BankCard", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", "Account")
                        .WithOne("Card")
                        .HasForeignKey("BankingApp.Domain.Entities.BankCard", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.CardRequest", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", "ApprovedAccount")
                        .WithMany()
                        .HasForeignKey("ApprovedAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BankingApp.Domain.Entities.BankCard", "ApprovedCard")
                        .WithMany()
                        .HasForeignKey("ApprovedCardId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("CardRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedAccount");

                    b.Navigation("ApprovedCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.CardRequestDocument", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.CardRequest", "CardRequest")
                        .WithMany("Documents")
                        .HasForeignKey("CardRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.ReferenceDataItem", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CardRequest");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Loan", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", "DestinationAccount")
                        .WithMany("Loans")
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.Transaction", "DisbursementTransaction")
                        .WithMany()
                        .HasForeignKey("DisbursementTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingApp.Domain.Entities.LoanApplication", "LoanApplication")
                        .WithOne("Loan")
                        .HasForeignKey("BankingApp.Domain.Entities.Loan", "LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationAccount");

                    b.Navigation("DisbursementTransaction");

                    b.Navigation("LoanApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanApplication", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", "DestinationAccount")
                        .WithMany("LoanApplications")
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.LoanProduct", "LoanProduct")
                        .WithMany("Applications")
                        .HasForeignKey("LoanProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.ReferenceDataItem", "LoanPurpose")
                        .WithMany()
                        .HasForeignKey("LoanPurposeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("LoanApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationAccount");

                    b.Navigation("LoanProduct");

                    b.Navigation("LoanPurpose");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanInstallment", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Loan", "Loan")
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.LoanPayment", "Payment")
                        .WithMany()
                        .HasForeignKey("LoanPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Loan");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanPayment", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.LoanInstallment", "LoanInstallment")
                        .WithMany()
                        .HasForeignKey("LoanInstallmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.Account", "SourceAccount")
                        .WithMany("LoanPayments")
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("LoanInstallment");

                    b.Navigation("SourceAccount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.ReportJob", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.ReferenceDataItem", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.TransactionDocument", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.ReferenceDataItem", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BankingApp.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Documents")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.Navigation("Card");

                    b.Navigation("LoanApplications");

                    b.Navigation("LoanPayments");

                    b.Navigation("Loans");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.CardRequest", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Loan", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanApplication", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LoanProduct", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("CardRequests");

                    b.Navigation("LoanApplications");

                    b.Navigation("Loans");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
